FROM docker.io/library/ubuntu:23.04 as base

RUN apt-get -qq update -y \
    && DEBIAN_FRONTEND=noninteractive \
       apt-get install -y --no-install-recommends \
               ca-certificates \
               clang \
               clang-format \
               git \
               golang \
               less \
               lld \
               llvm \
               make \
               vim \
    && rm -rf /var/lib/apt/lists/*
