FROM ghcr.io/tillitis/tkey-builder:2

RUN apt-get -qq update -y \
    && DEBIAN_FRONTEND=noninteractive \
       apt-get purge -y --auto-remove golang \
    && DEBIAN_FRONTEND=noninteractive \
       apt-get install -y --no-install-recommends \
               curl \
               software-properties-common \
    && add-apt-repository ppa:longsleep/golang-backports; \
    apt-get -qq update -y \
    && DEBIAN_FRONTEND=noninteractive \
       apt-get install -y --no-install-recommends \
               golang-1.20 \
    && rm -rf /var/lib/apt/lists/*

ENV PATH="$PATH:/usr/lib/go-1.20/bin"
