
name: ci

on:
  push:
    branches:
      - '*'
  pull_request: {}
  # allow manual runs:
  workflow_dispatch: {}

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/quite/tkey-apps-builder:1
      # https://github.com/actions/runner/issues/2033#issuecomment-1598547465
      options: --user 1001
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          #fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: build
        run: ./build.sh

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60.1

      # - name: check for SPDX tags
      #   run: ./tools/spdx-ensure
